# Generated by Django 6.0.7 on 2026-07-21 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('serial_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(max_length=100)),
                ('pricelist_id', models.IntegerField(db_index=True)),
                ('width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('env_temp_c', models.IntegerField(blank=True, null=True)),
                ('env_coated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='PriceListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricelist_id', models.IntegerField(db_index=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('order_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_entries', to='catalog.component')),
            ],
            options={
                'ordering': ['-order_time'],
                'indexes': [models.Index(fields=['pricelist_id', 'component'], name='catalog_pri_priceli_ff9df9_idx'), models.Index(fields=['order_time'], name='catalog_pri_order_t_b80751_idx')],
            },
        ),
    ]
