# Generated by Django 6.0.7 on 2026-07-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelistentry',
            name='order_time',
            field=models.DateField(),
        ),
    ]
